theme = "nord"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
cursorline = true
# cursorcolumn = true
auto-save = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner"]
center = ["file-name", "read-only-indicator", "version-control"]
right = ["diagnostics", "position", "position-percentage", "total-line-numbers"]

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"
skip-level = 0

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w75% -h75% -E gitui"
