# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[[battery.display]] 
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[kubernetes]
format = 'on [☸ ($cluster)\($context\) ](cyan) '
disabled = false

[shell]
disabled = true
